[appender.async_console]
kind = "async_console"
pattern = "%l %d{%H:%M:%S.%f} [%M #FS#%f#FE#:%L] %m"

[[appender.async_console.filter]]
kind = "threshold"
level = "info"

[appender.async_file]
kind = "async_file"
path = "Node.log"
pattern = "%l %d{%H:%M:%S.%f} [%M #FS#%f#FE#:%L] %m"
append = false

[root]
level = "error"
appenders = ["async_console", "async_file"]

[[logger]]
name = "crust"
level = "debug"
appenders = ["async_file"]
additive = false

[[logger]]
name = "routing"
level = "debug"

[[logger]]
name = "safe_vault"
level = "debug"
